In [ ]:
#Tushare库数据提取

In [3]:
##导入库部分
###import命令后面加as,后面使用对应命令时设置缩写
###导入tushare库
import tushare as ts
###导入pandas库-Python的一个数据结构包，方便后续进行数据存储和显示
import pandas as pd

In [3]:
##程序内容部分

In [4]:
###设置api接口,api接口用于与其他数据库对接，注册时会给予账号对应api信息，也决定所获得的权限，下面使用的是tushare网站给出的示例api接口，权限较低不过可以获取一些一般数据
###tushare网站过去完全免费，现在基本功能免费，部分高级功能对认证学生会员开放积分获取机制，可以尝试使用
pro = ts.pro_api('08e0747acd09a46936ae6ffb2a0d7fcaf4edaebad6aa33032481f5d0')

In [5]:
###使用tushare网站示例程序拉取数据，简单拉取全部a股上市公司基本信息并存入pandas表df
df = pro.stock_basic(**{
    "ts_code": "",
    "name": "",
    "exchange": "",
    "market": "",
    "is_hs": "",
    "list_status": "",
    "limit": "",
    "offset": ""
}, fields=[
    "ts_code",
    "symbol",
    "name",
    "area",
    "industry",
    "market",
    "list_date",
    "fullname",
    "enname",
    "cnspell",
    "exchange",
    "curr_type",
    "list_status",
    "delist_date",
    "is_hs"
])
print(df)

        ts_code  symbol     name  area industry         fullname  \
0     000001.SZ  000001     平安银行    深圳       银行       平安银行股份有限公司
1     000002.SZ  000002      万科A    深圳     全国地产       万科企业股份有限公司
2     000004.SZ  000004     国华网安    深圳     软件服务   深圳国华网安科技股份有限公司
3     000005.SZ  000005     ST星源    深圳     环境保护     深圳世纪星源股份有限公司
4     000006.SZ  000006     深振业A    深圳     区域地产  深圳市振业(集团)股份有限公司
...         ...     ...      ...   ...      ...              ...
4723  871553.BJ  871553     凯腾精工  None     None   北京凯腾精工制版股份有限公司
4724  871642.BJ  871642     通易航天  None     None   南通通易航天科技股份有限公司
4725  871981.BJ  871981     晶赛科技  None     None     安徽晶赛科技股份有限公司
4726  872925.BJ  872925     锦好医疗  None     None  惠州市锦好医疗科技股份有限公司
4727  689009.SH  689009  九号公司-WD    北京      摩托车           九号有限公司

                                                 enname  cnspell market  \
0                                Ping An Bank Co., Ltd.     payh     主板
1                                  China Vanke Co.,Ltd.      wka     主板
2     Shenzhen Guohua Network Security Technology Co...     ghwa     主板
3                         Shenzhen Fountain Corporation     stxy     主板
4                       Shenzhen Zhenye(Group) Co.,Ltd.     szya     主板
...                                                 ...      ...    ...
4723  Beijing Kaiteng Jinggong Gravure Cylinder Co.,...     ktjg    北交所
4724  Nantong Tongyi Aerospace Science and Technolog...     tyht    北交所
4725                 Anhui Jing Sai Technology Co., Ltd     jskj    北交所
4726        Huizhou Jinghao Medical Technology Co.,Ltd.     jhyl    北交所
4727                                    Ninebot Limited  jhgs-wd    CDR

     exchange curr_type list_status list_date delist_date is_hs
0        SZSE       CNY           L  19910403        None     S
1        SZSE       CNY           L  19910129        None     S
2        SZSE       CNY           L  19910114        None     N
3        SZSE       CNY           L  19901210        None     N
4        SZSE       CNY           L  19920427        None     S
...       ...       ...         ...       ...         ...   ...
4723      BSE       CNY           L  20210806        None     N
4724      BSE       CNY           L  20210816        None     N
4725      BSE       CNY           L  20211115        None     N
4726      BSE       CNY           L  20211025        None     N
4727      SSE       CNY           L  20201029        None  None

[4728 rows x 15 columns]

In [4]:
###行业排序,pandas库功能，对pandas表中列使用sort_values进行排序
df.sort_values('industry')

,ts_code,symbol,name,area,industry,fullname,enname,cnspell,market,exchange,curr_type,list_status,list_date,delist_date,is_hs
1522,300042.SZ,300042,朗科科技,深圳,IT设备,深圳市朗科科技股份有限公司,"Netac Technology Co., Ltd.",lkkj,创业板,SZSE,CNY,L,20100108,None,N
3191,600734.SH,600734,*ST实达,福建,IT设备,福建实达集团股份有限公司,"Fujian Start Group Co.,Ltd",stsd,主板,SSE,CNY,L,19960808,None,N
2259,300802.SZ,300802,矩子科技,上海,IT设备,上海矩子科技股份有限公司,"Jutze Intelligence Technology Co.,Ltd.",jzkj,创业板,SZSE,CNY,L,20191114,None,N
3078,600601.SH,600601,ST方科,上海,IT设备,方正科技集团股份有限公司,"Founder Technology Group Co., Ltd.",stfk,主板,SSE,CNY,L,19901219,None,N
2019,300551.SZ,300551,古鳌科技,上海,IT设备,上海古鳌电子科技股份有限公司,"Shanghai Guao Electronic Technology Co., Ltd.",gakj,创业板,SZSE,CNY,L,20161018,None,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4718,871396.BJ,871396,常辅股份,None,None,常州电站辅机股份有限公司,Changzhou Power Station Auxiliary Equipment Co...,cfgf,北交所,BSE,CNY,L,20201118,None,N
4719,871553.BJ,871553,凯腾精工,None,None,北京凯腾精工制版股份有限公司,"Beijing Kaiteng Jinggong Gravure Cylinder Co.,...",ktjg,北交所,BSE,CNY,L,20210806,None,N
4720,871642.BJ,871642,通易航天,None,None,南通通易航天科技股份有限公司,Nantong Tongyi Aerospace Science and Technolog...,tyht,北交所,BSE,CNY,L,20210816,None,N
4721,871981.BJ,871981,晶赛科技,None,None,安徽晶赛科技股份有限公司,"Anhui Jing Sai Technology Co., Ltd",jskj,北交所,BSE,CNY,L,20211115,None,N
4722,872925.BJ,872925,锦好医疗,None,None,惠州市锦好医疗科技股份有限公司,"Huizhou Jinghao Medical Technology Co.,Ltd.",jhyl,北交所,BSE,CNY,L,20211025,None,N

In [7]:
###pandas表简单查询
df[df['name']=='中兵红箭']
df[df['industry']=='环境保护']

,ts_code,symbol,name,area,industry,fullname,enname,cnspell,market,exchange,curr_type,list_status,list_date,delist_date,is_hs
3,000005.SZ,000005,ST星源,深圳,环境保护,深圳世纪星源股份有限公司,Shenzhen Fountain Corporation,stxy,主板,SZSE,CNY,L,19901210,None,N
27,000035.SZ,000035,中国天楹,江苏,环境保护,中国天楹股份有限公司,China Tianying Inc.,zgty,主板,SZSE,CNY,L,19940408,None,S
49,000068.SZ,000068,华控赛格,深圳,环境保护,深圳华控赛格股份有限公司,"Shenzhen Huakong Seg Co.,Ltd.",hksg,主板,SZSE,CNY,L,19970611,None,N
132,000544.SZ,000544,中原环保,河南,环境保护,中原环保股份有限公司,"Central Plains Environment Protection Co.,Ltd",zyhb,主板,SZSE,CNY,L,19931208,None,N
134,000546.SZ,000546,金圆股份,吉林,环境保护,金圆环保股份有限公司,"Jinyuan Ep Co.,Ltd",jygf,主板,SZSE,CNY,L,19931215,None,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4519,688501.SH,688501,青达环保,山东,环境保护,青岛达能环保设备股份有限公司,Qingdao Daneng Environmental Protection Equipm...,qdhb,科创板,SSE,CNY,L,20210716,None,N
4548,688565.SH,688565,力源科技,浙江,环境保护,浙江海盐力源环保科技股份有限公司,Zhejiang Haiyan Power System Resources Environ...,lykj,科创板,SSE,CNY,L,20210513,None,N
4593,688659.SH,688659,元琛科技,安徽,环境保护,安徽元琛环保科技股份有限公司,Anhui Yuanchen Environmental Protection Scienc...,yckj,科创板,SSE,CNY,L,20210331,None,N
4606,688679.SH,688679,通源环境,安徽,环境保护,安徽省通源环境节能股份有限公司,"Anhui Tongyuan Environment Energy Saving Co.,Ltd.",tyhj,科创板,SSE,CNY,L,20201225,None,N
4621,688701.SH,688701,卓锦股份,浙江,环境保护,浙江卓锦环保科技股份有限公司,"Zhejiang Zone-King Environmental Sci&Tech Co.,...",zjgf,科创板,SSE,CNY,L,20210916,None,N