In [ ]:
#pandas库简单读取excel进行处理

In [2]:
import pandas as pd

In [3]:
#申万行业分类表格提取
basestation ="swclass217.xlsx"
##pandas库提取excel命令.read_excel
data = pd.read_excel(basestation)
data

     交易所    行业代码       股票代码                公司简称 新版一级行业 新版二级行业 新版三级行业
0     A股  720902  600373.SH                 NaN     传媒     出版   大众出版
1     A股  720902  601949.SH                中国出版     传媒     出版   大众出版
2     A股  720902  601801.SH                皖新传媒     传媒     出版   大众出版
3     A股  720902  300788.SZ                中信出版     传媒     出版   大众出版
4     A股  720902  601858.SH                中国科传     传媒     出版   大众出版
...   ..     ...        ...                 ...    ...    ...    ...
5279  美股  240301      ACH.N                中国铝业   有色金属   工业金属      铝
5280  美股  240301     5EN.SG               麦达新控股   有色金属   工业金属      铝
5281  美股  240302    NUAG.TO  NEW PACIFIC METALS   有色金属   工业金属      铜
5282  美股  240402     SVM.TO             希尔威金属矿业   有色金属    贵金属     白银
5283  美股  240401     CGG.TO              中国黄金国际   有色金属    贵金属     黄金

[5284 rows x 7 columns]

In [4]:
#筛选特定行业
data[data['新版三级行业']=='种子']

     交易所    行业代码       股票代码  公司简称 新版一级行业 新版二级行业 新版三级行业
3046  A股  110101  000998.SZ  隆平高科   农林牧渔    种植业     种子
3047  A股  110101  002041.SZ  登海种业   农林牧渔    种植业     种子
3048  A股  110101  300087.SZ  荃银高科   农林牧渔    种植业     种子
3049  A股  110101  000713.SZ  丰乐种业   农林牧渔    种植业     种子
3050  A股  110101  600313.SH  农发种业   农林牧渔    种植业     种子
3051  A股  110101  300189.SZ  神农科技   农林牧渔    种植业     种子
3052  A股  110101  600371.SH  万向德农   农林牧渔    种植业     种子
3053  A股  110101  600354.SH  敦煌种业   农林牧渔    种植业     种子

In [5]:
#筛选特定公司
data[data['公司简称']=='双汇发展']

     交易所    行业代码       股票代码  公司简称 新版一级行业 新版二级行业 新版三级行业
3684  A股  340401  000895.SZ  双汇发展   食品饮料   食品加工    肉制品